### ISSUE TITLE
Remove if condition `()`

### ISSUE THREAD

**Issue by marcuswu0814** [marcuswu0814/RedmineBot#15]
Like this: https://github.com/marcuswu0814/RedmineBot/blob/15b2cd5f6f407ffe8c55465ac9b5fcae61af397d/Sources/RedmineBotCore/Command/InstallHookCommand.swift#L81

to

```swift
if !job.repoPath.exists {
```

**Comment by ganes1410** [comment]
@marcuswu0814  i made a pr
